# Generated by Django 4.1.7 on 2023-02-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(help_text="Post url", max_length=20, unique=True),
                ),
                ("content", models.JSONField()),
                ("likes_num", models.IntegerField()),
                ("comments_num", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "PROCESSING"), ("parsed", "PARSED")],
                        default="processing",
                        max_length=250,
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("parse_time", models.DateTimeField()),
            ],
        ),
    ]
