# Generated by Django 4.1.7 on 2023-02-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reddit_parser_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("processing", "PROCESSING"), ("parsed", "PARSED")],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.CharField(help_text="Post url", max_length=250, unique=True),
        ),
    ]
